### ISSUE TITLE
Release 2.4.0

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-collection-compat#413]
Motivations:

* [x] support Scala Native 0.4.0 on 2.11, 2.12, 2.13 (#387)  /cc @ekrich 
* [x] restore Scala 3.0.0-M2 support (#405)
* [x] deal with `@nowarn` (#397, #417)

Steps:

* [x] merge PRs
* [x] choose version number
  * let's call it 2.4.0, Scala Native support is a big deal, and 2.12.13 support is arguably a "feature" rather than a "fix" 
* [x] create the release and write the notes
  * https://github.com/scala/scala-collection-compat/releases/tag/v2.4.0
* [x] wait for release build
  * https://travis-ci.com/github/scala/scala-collection-compat/builds/214738364
* [x] release the staging repos
* [x] artifacts on Maven Central
  * https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_3.0.0-M3/2.4.0/
  * https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_3.0.0-M2/2.4.0/
  * https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_2.13/2.4.0/
  * https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_2.12/2.4.0/
  * https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_2.11/2.4.0/
* [x] post-release, bump version in README
  * 463ee206820e1d0c0a0d123df8b768c381d2427a

**Comment by lolgab** [comment]
Is there an ETA for this release?
You should probably merge [this one](https://github.com/scala/scala-collection-compat/pull/415) first.

**Comment by SethTisue** [comment]
If I don't get to it today, then early next week.

**Comment by lolgab** [comment]
@SethTisue Cool, thank you! 🙏

**Comment by SethTisue** [comment]
the 3.0.0-M2 artifacts haven't shown up on Maven Central, but the others have. hopefully it's just that some extra patience is needed...

**Comment by sideeffffect** [comment]
Is it possible that just because of some change from `2.3.2` to `2.4.0` I'm suddenly getting errors like this
```
[error] /home/runner/work/izumi-reflect/izumi-reflect/izumi-reflect/izumi-reflect/src/main/scala/izumi/reflect/internal/fundamentals/collections/IzMappings.scala:26:4: expected literal string as @nowarn annotation argument
[error]   @nowarn("msg=deprecated")
[error]    ^
```
?

**Comment by ekrich** [comment]
Working for JVM and JS 2.11 - 3.0.0-M3 (no M2) and Native 2.11 - 2.13 for `ekrich/sconfig`. Thanks!

**Comment by SethTisue** [comment]
@sideeffffect presumably related to #417 — please open a ticket with details, what Scala version(s) are affected, whether it happens on JVM or JS or Native all three, etc etc

**Comment by jodersky** [comment]
Would it be possible to also publish 2.4.0 for scala js 0.6?

**Comment by SethTisue** [comment]
@jodersky hmm, well I'd honestly really rather not. at least not unless it's creating some kind of serious roadblock for actual 0.6 users. is there a real need for 0.6 users not to just leave the dependency frozen at whatever version they're already on? most of the repos I'm involved with dropped 0.6 support a while ago

**Comment by SethTisue** [comment]
> the 3.0.0-M2 artifacts haven't shown up on Maven Central, but the others have. hopefully it's just that some extra patience is needed...

nope. Sonatype just.... disappeared them, like mobsters disappearing a murder witness

or maybe I'm jumping to conclusions and there is somehow something wrong in the build? https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_sjs1_3.0.0-M2/2.4.0/ is also missing

over at https://travis-ci.com/github/scala/scala-collection-compat/builds/214738364 , I hit restart on both M2 jobs, which should make them publish again, to new staging repos

new logs:
* https://travis-ci.com/github/scala/scala-collection-compat/jobs/476713037
* https://travis-ci.com/github/scala/scala-collection-compat/jobs/476713038

aha! the jobs say M2 on them, but the artifacts say M3. I apologize to the Sonatype-American community.

let's take a closer look at https://travis-ci.com/github/scala/scala-collection-compat/jobs/476713037

it does have `TRAVIS_SCALA_VERSION -> 3.0.0-M2`

but then `[info] compiling 19 Scala sources to /home/travis/build/scala/scala-collection-compat/.cross/compat30/jvm/target/scala-3.0.0-M3/test-classes ...`

so I guess this has something to do with the weird way this repo is set up (#395 is where we complain about that)

and aha, `build.sbt` has `lazy val scala30  = "3.0.0-M3"` and it does `val compatProject       = "compat" + travisScalaVersion.get.binary + platformSuffix` but otherwise ignores `travisScalaVersion`

okay, I'll PR a fix

**Comment by SethTisue** [comment]
https://github.com/scala/scala-collection-compat/pull/420 🌿

**Comment by SethTisue** [comment]
Because publishing is weird in this repo, I don't trust myself to attempt to back-publish, and anyway I want to be sure that full publishing is still working. So I'm going to roll 2.14.1: #422
